import { useUser, SignInButton, SignOutButton } from "@clerk/nextjs";
import Image from "next/image";
import dayjs from "dayjs";
import Head from "next/head";
import relativeTime from "dayjs/plugin/relativeTime"

import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";


dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;

  return (
    <div className="flex gap-10">
      <Image
        src={user.imageUrl}
        alt="profile-picture"
        className="w-14 h-14 rounded-full"
        width={56}
        height={56}
      />
      <input
        placeholder="Type some emojis"
        className="bg-transparent grow"

      />
    </div>
  )
}

type PostWithUser = RouterOutputs["post"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div
      key={post.id}
      className="border-b border-slate-400 p-8 flex gap-3"
    >
      <Image
        src={author.imageUrl}
        alt={`${author.username} profile picture`}
        className="h-12 w-12 rounded-full"
        width={56}
        height={56}
      />
      <div className="flex flex-col text-slate-200">
        <div className="flex">
          <span>{`${author.username}`}</span>
          <span>{`· ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        {post.content}
      </div>
    </div>
  )
}

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.post.getAll.useQuery()

  if (isLoading) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl bg-red border-x border-slate-400">
          <div className="flex border-b border-slate-400 p-4 justify-between">
            {!user.isSignedIn &&
              <div className="flex justify-center">
                <SignInButton />
              </div>
            }
            {!!user.isSignedIn && (
                <CreatePostWizard />
            )}
          </div>
          <div>
            <div>
              {
                data?.map((fullPost) => (
                  <PostView {...fullPost} key={fullPost.post.id} />
                ))
              }
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
