import { useUser, SignInButton, SignOutButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.post.getAll.useQuery()
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex justify-center">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <div className="bg-red-200">
          <div>
            {
              data?.map((post) => (
                <div key={post.id}>
                  {post.content}
                </div>
              ))
            }
          </div>
        </div>
      </main>
    </>
  );
}
